name: Deploy to Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # deploy to aliyun dev environment
  deploy:
    runs-on: ubuntu-latest    
    environment: dev # specifing environment is necessary for corresponding secrets and vars
    steps:
      - name: Deploy to Aliyun Dev environment # Specify a name for each step, which will show up on github action dashboard
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ vars.CODE_PATH }}
            git checkout main
            git pull